# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab00facf596b28a5a242ad727964dce38541ee0f22aeda0c1048546a3eb081288582dd641db433265b69c8a8a69bc984852640cb4bca4b83ce7c36acdc8e7ea0

test:
  secret_key_base: 0d21bc923941dd7687f8b7131ef8ca82f9474f6199f9e413b99bf0115ee57e8a918491916922f44503517aa02138deb60f33e9fbe50081f6d9216b3295d63142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
